### ISSUE TITLE
add-path is deprecated

### ISSUE THREAD

**Issue by NivedhaSenthil** [Geertvdc/setup-hub#10]
add-path command is deprecated by github actions, which is used by setup-hub. Below is the error received in actions

Error: Unable to process command '##[add-path]/opt/hostedtoolcache/hub/2.14.2/x64/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by salexander6** [comment]
See https://github.com/Geertvdc/setup-hub/issues/9

**Comment by NivedhaSenthil** [comment]
Thanks for the quick response ... will check using the pre installed hub.
