### ISSUE TITLE
Builds fail due to deprecated use of add-path

### ISSUE THREAD

**Issue by jakzal** [Geertvdc/setup-hub#9]
Github deprecated `set-env` and `add-path` commands: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Builds that use setup-hub started failing with:

```
Error: Unable to process command '##[add-path]/opt/hostedtoolcache/hub/2.14.2/x64/bin' successfully.
5
Error: The `add-path` command is disabled. 
Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`.
For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by mvrska** [comment]
I too had this issue but I found that there is probably? no need for this action anymore.

I just removed it from the yamls and it continued working. hub seems to be available regardless

**Comment by isen-ng** [comment]
According to https://github.com/github/hub#github-actions , hub is already pre-installed in actions.
I will test this tonight when my daily action runs.

**Comment by jakzal** [comment]
I can also confirm hub is now installed by default, which makes this action redundant. Thanks everyone!
